version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:2.479.3-lts-jdk17
    network_mode: "host"
    container_name: jenkins
    environment:
      - TZ=Asia/Seoul
    user: root
    privileged: true
    volumes:
      - ./jenkins/config:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
      - 50000:50000
