name: Run Pytest

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies for `app`
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Run Pytest in `app` directory
        working-directory: app
        run: |
          pytest
